export function getOrderData() {
  return [
    {
      destinationAddress: "王府井",
      id: 0,
      inCarNum: 0,
      lineCode: "",
      lineId: 0,
      lineName: "",
      orderNum: 38,
      originAddress: "王府井",
      overNum: 10,
      payTime: "",
      refundNum: 0,
      seatNum: 0,
      toBeCarNum: 0,
      toBePayNum: 0,
      yearMonth: "01",
    },
    {
      destinationAddress: "市政府",
      id: 0,
      inCarNum: 0,
      lineCode: "",
      lineId: 0,
      lineName: "",
      orderNum: 20,
      originAddress: "市政府",
      overNum: 20,
      payTime: "",
      refundNum: 0,
      seatNum: 0,
      toBeCarNum: 0,
      toBePayNum: 0,
      yearMonth: "02",
    },
    {
      destinationAddress: "火车南",
      id: 0,
      inCarNum: 0,
      lineCode: "",
      lineId: 0,
      lineName: "",
      orderNum: 45,
      originAddress: "火车南",
      overNum: 30,
      payTime: "",
      refundNum: 0,
      seatNum: 0,
      toBeCarNum: 0,
      toBePayNum: 0,
      yearMonth: "03",
    },
    {
      destinationAddress: "飞机场",
      id: 0,
      inCarNum: 0,
      lineCode: "",
      lineId: 0,
      lineName: "",
      orderNum: 63,
      originAddress: "飞机场",
      overNum: 50,
      payTime: "",
      refundNum: 0,
      seatNum: 0,
      toBeCarNum: 0,
      toBePayNum: 0,
      yearMonth: "04",
    }
  ];
}

export function getSeatRatioData() {
  return [
    {
      capacity: 0,
      id: "",
      seatRatio: 30,
      soldSeats: 0,
      tripNum: 0,
      vehicleNo: "鲁827681",
    },
    {
      capacity: 0,
      id: "",
      seatRatio: 30,
      soldSeats: 0,
      tripNum: 0,
      vehicleNo: "鲁827681",
    },
    {
      capacity: 0,
      id: "",
      seatRatio: 50,
      soldSeats: 0,
      tripNum: 0,
      vehicleNo: "鲁827681",
    },
    {
      capacity: 0,
      id: "",
      seatRatio: 60,
      soldSeats: 0,
      tripNum: 0,
      vehicleNo: "鲁827681",
    },
  ];
}

export function getOnlineData() {
  return [
    {
      actualArriveTime: "",
      customerNum: 0,
      id: 0,
      lineCode: "",
      lineId: 0,
      lineName: "线路1",
      planDepartTime: "19:30",
      runStatus: 0,
      vehicleColour: "",
      vehicleId: "",
      vehicleModel: "",
      vehicleNo: "鲁982873",
      vehicleType: 0,
    },
  ];
}
